name: Data Preprocessing Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'churn_raw/**'
      - 'preprocessing/automate_*.py'
      - '.github/workflows/preprocessing.yml'

permissions:
  contents: write

jobs:
  build-and-preprocess:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12.7
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.7'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas scikit-learn

      - name: Run preprocessing script
        # Mengeksekusi file Python dengan nama yang sudah diperbarui
        run: |
          python preprocessing/automate_Shandy_Putraniar_Budianto.py 

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add churn_preprocessing/
          git commit -m "Auto-preprocess data via GitHub Actions" -a || echo "No changes to commit"
          git push